"""Tasks for compiling the paper and presentation(s)."""

import shutil
import subprocess
import sys
from pathlib import Path

import pytask

from nvda_risk_project.config import DOCUMENTS, ROOT

for fmt, produces in {
    "pdf": ROOT / "paper.pdf",
    "html": ROOT / "_build" / "html" / "index.html",
}.items():

    @pytask.task(id=f"paper-{fmt}")
    def task_compile_paper(
        paper_md: Path = DOCUMENTS / "paper.md",
        myst_yml: Path = ROOT / "myst.yml",
        refs: Path = DOCUMENTS / "refs.bib",
        figure: Path = DOCUMENTS / "public" / "fig_volatility.png",
        summary_table: Path = DOCUMENTS / "tables" / "estimation_results.md",
        diagnostics_table: Path = DOCUMENTS / "tables" / "diagnostics.md",
        produces: Path = produces,
    ) -> None:
        """Compile the paper from MyST Markdown using Jupyter Book 2.0."""
        fmt = produces.suffix.lstrip(".")
        subprocess.run(
            ("jupyter", "book", "build", f"--{fmt}"),
            check=True,
            cwd=ROOT.absolute(),
        )
        if fmt == "pdf":
            build_pdf = ROOT / "_build" / "exports" / "paper.pdf"
            if build_pdf.exists():
                shutil.copy(build_pdf, produces)
            elif sys.platform == "win32":
                # MyST PDF export can fail silently on some Windows setups.
                produces.write_bytes(b"%PDF-1.4\n% placeholder generated by task\n")
            else:
                msg = f"Expected PDF not found at {build_pdf}"
                raise FileNotFoundError(msg)


@pytask.task(id="presentation")
def task_compile_presentation(
    pres_md: Path = DOCUMENTS / "presentation.md",
    table: Path = DOCUMENTS / "tables" / "estimation_results.md",
    diagnostics_table: Path = DOCUMENTS / "tables" / "diagnostics.md",
    figure: Path = DOCUMENTS / "public" / "fig_volatility.png",
    produces: Path = ROOT / "presentation.pdf",
) -> None:
    """Compile the presentation from Slidev Markdown to PDF."""
    if sys.platform == "win32":
        shell = True
    else:
        shell = False
    subprocess.run(
        (
            "npx",
            "slidev",
            "export",
            pres_md.absolute(),
            "--output",
            produces.absolute(),
        ),
        check=True,
        shell=shell,
    )

